name: upvoty_example
description: Demonstrates how to use the upvoty plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  upvoty:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: NunitoSans
      fonts:
        - asset: res/NunitoSans-Black.ttf
          weight: 900
        - asset: res/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: res/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/NunitoSans-Bold.ttf
          weight: 700
        - asset: res/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: res/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/NunitoSans-Regular.ttf
          weight: 400
        - asset: res/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: res/NunitoSans-Light.ttf
          weight: 300
        - asset: res/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: res/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic