name: upvoty
description: flutter lib for upvoty
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/upvoty
issue_tracker: https://github.com/tiki/upvoty/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: