/// Flutter icons UpvotyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UpvotyIcons
///      fonts:
///       - asset: fonts/UpvotyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UpvotyIcons {
  UpvotyIcons._();

  static const _kFontFam = 'UpvotyIcons';
  static const String? _kFontPkg = 'upvoty';

  static const IconData left_arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
